2020-08-31 20:29:12,072 ERROR: Exception on /hansard [GET] [in /Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/michellewong/Documents/Speakup/app/routes.py", line 199, in hansard
    for child in root:
UnboundLocalError: local variable 'root' referenced before assignment
2020-08-31 20:30:32,152 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-08-31 20:36:24,253 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-08-31 20:36:45,975 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-08-31 20:36:51,442 ERROR: Exception on /hansard [GET] [in /Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/michellewong/Documents/Speakup/app/routes.py", line 204, in hansard
    return render_template('hansard.html',data = headings_dict)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
<<<<<<< HEAD
  File "/Users/michellewong/Documents/Speakup/app/templates/yourrep.html", line 1, in top-level template code
    {% extends "navbar.html" %}
  File "/Users/michellewong/Documents/Speakup/app/templates/navbar.html", line 51, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/michellewong/Documents/Speakup/app/templates/yourrep.html", line 84, in block "content"
    {{data.name.first}} {{data.name.last}}
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'name'
2020-08-31 12:23:06,417 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-08-31 12:24:26,012 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-01 09:48:23,246 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
=======
  File "/Users/michellewong/Documents/Speakup/app/templates/hansard.html", line 67, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2020-08-31 20:38:07,499 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-01 08:17:13,161 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-01 08:18:15,976 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-01 08:22:07,793 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-01 08:23:07,149 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-01 08:24:05,046 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-01 08:25:13,643 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-01 08:25:37,402 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-01 08:25:57,301 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-01 08:26:42,188 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-01 08:27:08,159 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-01 08:27:39,076 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
>>>>>>> 57a0999... representative profile and other stuff
